Traceback (most recent call last):
  File "/usr/local/pyenv/versions/3.9.8/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/usr/local/pyenv/versions/3.9.8/lib/python3.9/site-packages/nbclient/client.py", line 1085, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/local/pyenv/versions/3.9.8/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/local/pyenv/versions/3.9.8/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/local/pyenv/versions/3.9.8/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/usr/local/pyenv/versions/3.9.8/lib/python3.9/site-packages/nbclient/client.py", line 551, in async_execute
    await self.async_execute_cell(
  File "/usr/local/pyenv/versions/3.9.8/lib/python3.9/site-packages/nbclient/client.py", line 846, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/usr/local/pyenv/versions/3.9.8/lib/python3.9/site-packages/nbclient/client.py", line 748, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from oggm.utils import write_centerlines_to_shape

write_centerlines_to_shape(gdirs,  # The glaciers to process
                           path='outputs/Norway_Centerlines.shp',  # The output file
                           to_tar=False,  # set to True to put everything into one single tar file
                           to_crs=inventory.crs,  # Write into the projection of the original inventory
                           keep_main_only=True,  # Write only the main flowline and discard the tributaries
                          )
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mTypeError[0m                                 Traceback (most recent call last)
[0;32m/tmp/ipykernel_770/3745174353.py[0m in [0;36m<module>[0;34m[0m
[1;32m      1[0m [0;32mfrom[0m [0moggm[0m[0;34m.[0m[0mutils[0m [0;32mimport[0m [0mwrite_centerlines_to_shape[0m[0;34m[0m[0;34m[0m[0m
[1;32m      2[0m [0;34m[0m[0m
[0;32m----> 3[0;31m write_centerlines_to_shape(gdirs,  # The glaciers to process
[0m[1;32m      4[0m                            [0mpath[0m[0;34m=[0m[0;34m'outputs/Norway_Centerlines.shp'[0m[0;34m,[0m  [0;31m# The output file[0m[0;34m[0m[0;34m[0m[0m
[1;32m      5[0m                            [0mto_tar[0m[0;34m=[0m[0;32mFalse[0m[0;34m,[0m  [0;31m# set to True to put everything into one single tar file[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/local/pyenv/versions/3.9.8/lib/python3.9/site-packages/oggm/utils/_workflow.py[0m in [0;36m_global_task[0;34m(gdirs, **kwargs)[0m
[1;32m    546[0m [0;34m[0m[0m
[1;32m    547[0m             [0;31m# Run the task[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 548[0;31m             [0;32mreturn[0m [0mtask_func[0m[0;34m([0m[0mgdirs[0m[0;34m,[0m [0;34m**[0m[0mkwargs[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    549[0m [0;34m[0m[0m
[1;32m    550[0m         [0m_global_task[0m[0;34m.[0m[0m__dict__[0m[0;34m[[0m[0;34m'is_global_task'[0m[0;34m][0m [0;34m=[0m [0;32mTrue[0m[0;34m[0m[0;34m[0m[0m

[0;31mTypeError[0m: write_centerlines_to_shape() got an unexpected keyword argument 'to_crs'
TypeError: write_centerlines_to_shape() got an unexpected keyword argument 'to_crs'

