Traceback (most recent call last):
  File "/usr/local/pyenv/versions/3.10.10/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/usr/local/pyenv/versions/3.10.10/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/local/pyenv/versions/3.10.10/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/local/pyenv/versions/3.10.10/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/local/pyenv/versions/3.10.10/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/usr/local/pyenv/versions/3.10.10/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/usr/local/pyenv/versions/3.10.10/lib/python3.10/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/usr/local/pyenv/versions/3.10.10/lib/python3.10/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Let's make a working directory for this DEM 
cfg.PATHS['working_dir'] = utils.gettempdir('gimp', reset=True)
try:
    gdir = workflow.init_glacier_directories(entity)[0]
    tasks.define_glacier_region(gdir, source='GIMP')
except oggm.exceptions.InvalidDEMError as err:
    print(err)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mInvalidWorkflowError[0m                      Traceback (most recent call last)
Cell [0;32mIn[13], line 5[0m
[1;32m      3[0m [38;5;28;01mtry[39;00m:
[1;32m      4[0m     gdir [38;5;241m=[39m workflow[38;5;241m.[39minit_glacier_directories(entity)[[38;5;241m0[39m]
[0;32m----> 5[0m     [43mtasks[49m[38;5;241;43m.[39;49m[43mdefine_glacier_region[49m[43m([49m[43mgdir[49m[43m,[49m[43m [49m[43msource[49m[38;5;241;43m=[39;49m[38;5;124;43m'[39;49m[38;5;124;43mGIMP[39;49m[38;5;124;43m'[39;49m[43m)[49m
[1;32m      6[0m [38;5;28;01mexcept[39;00m oggm[38;5;241m.[39mexceptions[38;5;241m.[39mInvalidDEMError [38;5;28;01mas[39;00m err:
[1;32m      7[0m     [38;5;28mprint[39m(err)

File [0;32m/usr/local/pyenv/versions/3.10.10/lib/python3.10/site-packages/oggm/utils/_workflow.py:491[0m, in [0;36mentity_task.__call__.<locals>._entity_task[0;34m(gdir, reset, print_log, return_value, continue_on_error, add_to_log_file, **kwargs)[0m
[1;32m    489[0m     signal[38;5;241m.[39malarm(cfg[38;5;241m.[39mPARAMS[[38;5;124m'[39m[38;5;124mtask_timeout[39m[38;5;124m'[39m])
[1;32m    490[0m ex_t [38;5;241m=[39m time[38;5;241m.[39mtime()
[0;32m--> 491[0m out [38;5;241m=[39m [43mtask_func[49m[43m([49m[43mgdir[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m
[1;32m    492[0m ex_t [38;5;241m=[39m time[38;5;241m.[39mtime() [38;5;241m-[39m ex_t
[1;32m    493[0m [38;5;28;01mif[39;00m cfg[38;5;241m.[39mPARAMS[[38;5;124m'[39m[38;5;124mtask_timeout[39m[38;5;124m'[39m] [38;5;241m>[39m [38;5;241m0[39m:

File [0;32m/usr/local/pyenv/versions/3.10.10/lib/python3.10/site-packages/oggm/core/gis.py:345[0m, in [0;36mdefine_glacier_region[0;34m(gdir, entity, source)[0m
[1;32m    342[0m     source_exists [38;5;241m=[39m is_dem_source_available(source, [38;5;241m*[39mgdir[38;5;241m.[39mextent_ll)
[1;32m    344[0m [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m source_exists:
[0;32m--> 345[0m     [38;5;28;01mraise[39;00m InvalidWorkflowError([38;5;124mf[39m[38;5;124m'[39m[38;5;124mSource: [39m[38;5;132;01m{[39;00msource[38;5;132;01m}[39;00m[38;5;124m is not available for [39m[38;5;124m'[39m
[1;32m    346[0m                                [38;5;124mf[39m[38;5;124m'[39m[38;5;124mglacier [39m[38;5;132;01m{[39;00mgdir[38;5;241m.[39mrgi_id[38;5;132;01m}[39;00m[38;5;124m with border [39m[38;5;124m'[39m
[1;32m    347[0m                                [38;5;124mf[39m[38;5;124m"[39m[38;5;132;01m{[39;00mcfg[38;5;241m.[39mPARAMS[[38;5;124m'[39m[38;5;124mborder[39m[38;5;124m'[39m][38;5;132;01m}[39;00m[38;5;124m"[39m)
[1;32m    348[0m dem_list, dem_source [38;5;241m=[39m get_topo_file((minlon, maxlon), (minlat, maxlat),
[1;32m    349[0m                                      rgi_id[38;5;241m=[39mgdir[38;5;241m.[39mrgi_id,
[1;32m    350[0m                                      dx_meter[38;5;241m=[39mdx,
[1;32m    351[0m                                      source[38;5;241m=[39msource)
[1;32m    352[0m log[38;5;241m.[39mdebug([38;5;124m'[39m[38;5;124m([39m[38;5;132;01m%s[39;00m[38;5;124m) DEM source: [39m[38;5;132;01m%s[39;00m[38;5;124m'[39m, gdir[38;5;241m.[39mrgi_id, dem_source)

[0;31mInvalidWorkflowError[0m: Source: GIMP is not available for glacier RGI60-11.00897 with border 10
InvalidWorkflowError: Source: GIMP is not available for glacier RGI60-11.00897 with border 10

