Traceback (most recent call last):
  File "/usr/local/pyenv/versions/3.10.10/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/usr/local/pyenv/versions/3.10.10/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/local/pyenv/versions/3.10.10/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/local/pyenv/versions/3.10.10/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/local/pyenv/versions/3.10.10/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/usr/local/pyenv/versions/3.10.10/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/usr/local/pyenv/versions/3.10.10/lib/python3.10/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/usr/local/pyenv/versions/3.10.10/lib/python3.10/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# file identifier where the model output is saved
file_id = '_ct'
tasks.run_with_hydro(gdir, run_task=tasks.run_constant_climate, nyears=100, y0=2014, halfsize=5, store_monthly_hydro=True, 
                     output_filesuffix=file_id);
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mKeyError[0m                                  Traceback (most recent call last)
File [0;32m/usr/local/pyenv/versions/3.10.10/lib/python3.10/site-packages/oggm/core/massbalance.py:368[0m, in [0;36mPastMassBalance.__init__[0;34m(self, gdir, mu_star, bias, filename, input_filesuffix, repeat, ys, ye, check_calib_params)[0m
[1;32m    367[0m [38;5;28;01mtry[39;00m:
[0;32m--> 368[0m     prcp_fac [38;5;241m=[39m [43mgdir[49m[38;5;241;43m.[39;49m[43mread_json[49m[43m([49m[38;5;124;43m'[39;49m[38;5;124;43mlocal_mustar[39;49m[38;5;124;43m'[39;49m[43m)[49m[43m[[49m[38;5;124;43m'[39;49m[38;5;124;43mglacier_prcp_scaling_factor[39;49m[38;5;124;43m'[39;49m[43m][49m
[1;32m    369[0m [38;5;28;01mexcept[39;00m [38;5;167;01mKeyError[39;00m:

[0;31mKeyError[0m: 'glacier_prcp_scaling_factor'

During handling of the above exception, another exception occurred:

[0;31mInvalidWorkflowError[0m                      Traceback (most recent call last)
Cell [0;32mIn[7], line 3[0m
[1;32m      1[0m [38;5;66;03m# file identifier where the model output is saved[39;00m
[1;32m      2[0m file_id [38;5;241m=[39m [38;5;124m'[39m[38;5;124m_ct[39m[38;5;124m'[39m
[0;32m----> 3[0m [43mtasks[49m[38;5;241;43m.[39;49m[43mrun_with_hydro[49m[43m([49m[43mgdir[49m[43m,[49m[43m [49m[43mrun_task[49m[38;5;241;43m=[39;49m[43mtasks[49m[38;5;241;43m.[39;49m[43mrun_constant_climate[49m[43m,[49m[43m [49m[43mnyears[49m[38;5;241;43m=[39;49m[38;5;241;43m100[39;49m[43m,[49m[43m [49m[43my0[49m[38;5;241;43m=[39;49m[38;5;241;43m2014[39;49m[43m,[49m[43m [49m[43mhalfsize[49m[38;5;241;43m=[39;49m[38;5;241;43m5[39;49m[43m,[49m[43m [49m[43mstore_monthly_hydro[49m[38;5;241;43m=[39;49m[38;5;28;43;01mTrue[39;49;00m[43m,[49m[43m [49m
[1;32m      4[0m [43m                     [49m[43moutput_filesuffix[49m[38;5;241;43m=[39;49m[43mfile_id[49m[43m)[49m;

File [0;32m/usr/local/pyenv/versions/3.10.10/lib/python3.10/site-packages/oggm/utils/_workflow.py:491[0m, in [0;36mentity_task.__call__.<locals>._entity_task[0;34m(gdir, reset, print_log, return_value, continue_on_error, add_to_log_file, **kwargs)[0m
[1;32m    489[0m     signal[38;5;241m.[39malarm(cfg[38;5;241m.[39mPARAMS[[38;5;124m'[39m[38;5;124mtask_timeout[39m[38;5;124m'[39m])
[1;32m    490[0m ex_t [38;5;241m=[39m time[38;5;241m.[39mtime()
[0;32m--> 491[0m out [38;5;241m=[39m [43mtask_func[49m[43m([49m[43mgdir[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m
[1;32m    492[0m ex_t [38;5;241m=[39m time[38;5;241m.[39mtime() [38;5;241m-[39m ex_t
[1;32m    493[0m [38;5;28;01mif[39;00m cfg[38;5;241m.[39mPARAMS[[38;5;124m'[39m[38;5;124mtask_timeout[39m[38;5;124m'[39m] [38;5;241m>[39m [38;5;241m0[39m:

File [0;32m/usr/local/pyenv/versions/3.10.10/lib/python3.10/site-packages/oggm/core/flowline.py:3792[0m, in [0;36mrun_with_hydro[0;34m(gdir, run_task, store_monthly_hydro, fixed_geometry_spinup_yr, ref_area_from_y0, ref_area_yr, ref_geometry_filesuffix, **kwargs)[0m
[1;32m   3789[0m [38;5;28;01mif[39;00m fixed_geometry_spinup_yr [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m:
[1;32m   3790[0m     kwargs[[38;5;124m'[39m[38;5;124mfixed_geometry_spinup_yr[39m[38;5;124m'[39m] [38;5;241m=[39m fixed_geometry_spinup_yr
[0;32m-> 3792[0m out [38;5;241m=[39m [43mrun_task[49m[43m([49m[43mgdir[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m
[1;32m   3794[0m [38;5;28;01mif[39;00m out [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m:
[1;32m   3795[0m     [38;5;28;01mraise[39;00m InvalidWorkflowError([38;5;124m'[39m[38;5;124mThe run task ([39m[38;5;132;01m{}[39;00m[38;5;124m) did not run [39m[38;5;124m'[39m
[1;32m   3796[0m                                [38;5;124m'[39m[38;5;124msuccessfully.[39m[38;5;124m'[39m[38;5;241m.[39mformat(run_task[38;5;241m.[39m[38;5;18m__name__[39m))

File [0;32m/usr/local/pyenv/versions/3.10.10/lib/python3.10/site-packages/oggm/utils/_workflow.py:491[0m, in [0;36mentity_task.__call__.<locals>._entity_task[0;34m(gdir, reset, print_log, return_value, continue_on_error, add_to_log_file, **kwargs)[0m
[1;32m    489[0m     signal[38;5;241m.[39malarm(cfg[38;5;241m.[39mPARAMS[[38;5;124m'[39m[38;5;124mtask_timeout[39m[38;5;124m'[39m])
[1;32m    490[0m ex_t [38;5;241m=[39m time[38;5;241m.[39mtime()
[0;32m--> 491[0m out [38;5;241m=[39m [43mtask_func[49m[43m([49m[43mgdir[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m
[1;32m    492[0m ex_t [38;5;241m=[39m time[38;5;241m.[39mtime() [38;5;241m-[39m ex_t
[1;32m    493[0m [38;5;28;01mif[39;00m cfg[38;5;241m.[39mPARAMS[[38;5;124m'[39m[38;5;124mtask_timeout[39m[38;5;124m'[39m] [38;5;241m>[39m [38;5;241m0[39m:

File [0;32m/usr/local/pyenv/versions/3.10.10/lib/python3.10/site-packages/oggm/core/flowline.py:3553[0m, in [0;36mrun_constant_climate[0;34m(gdir, nyears, y0, halfsize, bias, temperature_bias, precipitation_factor, store_monthly_step, store_model_geometry, store_fl_diagnostics, init_model_filesuffix, init_model_yr, output_filesuffix, climate_filename, mb_model, climate_input_filesuffix, init_model_fls, zero_initial_glacier, use_avg_climate, **kwargs)[0m
[1;32m   3550[0m     mb_model_class [38;5;241m=[39m ConstantMassBalance
[1;32m   3552[0m [38;5;28;01mif[39;00m mb_model [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m:
[0;32m-> 3553[0m     mb_model [38;5;241m=[39m [43mMultipleFlowlineMassBalance[49m[43m([49m[43mgdir[49m[43m,[49m
[1;32m   3554[0m [43m                                           [49m[43mmb_model_class[49m[38;5;241;43m=[39;49m[43mmb_model_class[49m[43m,[49m
[1;32m   3555[0m [43m                                           [49m[43my0[49m[38;5;241;43m=[39;49m[43my0[49m[43m,[49m[43m [49m[43mhalfsize[49m[38;5;241;43m=[39;49m[43mhalfsize[49m[43m,[49m
[1;32m   3556[0m [43m                                           [49m[43mbias[49m[38;5;241;43m=[39;49m[43mbias[49m[43m,[49m
[1;32m   3557[0m [43m                                           [49m[43mfilename[49m[38;5;241;43m=[39;49m[43mclimate_filename[49m[43m,[49m
[1;32m   3558[0m [43m                                           [49m[43minput_filesuffix[49m[38;5;241;43m=[39;49m[43mclimate_input_filesuffix[49m[43m)[49m
[1;32m   3560[0m [38;5;28;01mif[39;00m temperature_bias [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m:
[1;32m   3561[0m     mb_model[38;5;241m.[39mtemp_bias [38;5;241m=[39m temperature_bias

File [0;32m/usr/local/pyenv/versions/3.10.10/lib/python3.10/site-packages/oggm/core/massbalance.py:1272[0m, in [0;36mMultipleFlowlineMassBalance.__init__[0;34m(self, gdir, fls, mu_star, mb_model_class, use_inversion_flowlines, input_filesuffix, bias, **kwargs)[0m
[1;32m   1267[0m             [38;5;28;01mraise[39;00m InvalidParamsError([38;5;124m'[39m[38;5;124mt_star has not been set for this [39m[38;5;124m'[39m
[1;32m   1268[0m                                      [38;5;124m'[39m[38;5;124mglacier. Please set `y0` explicitly[39m[38;5;124m'[39m)
[1;32m   1269[0m         kwargs[[38;5;124m'[39m[38;5;124my0[39m[38;5;124m'[39m] [38;5;241m=[39m y0
[1;32m   1271[0m     [38;5;28mself[39m[38;5;241m.[39mflowline_mb_models[38;5;241m.[39mappend(
[0;32m-> 1272[0m         [43mmb_model_class[49m[43m([49m[43mgdir[49m[43m,[49m[43m [49m[43mmu_star[49m[38;5;241;43m=[39;49m[43mfl[49m[38;5;241;43m.[39;49m[43mmu_star[49m[43m,[49m[43m [49m[43mbias[49m[38;5;241;43m=[39;49m[43mfl_bias[49m[43m,[49m
[1;32m   1273[0m [43m                       [49m[43minput_filesuffix[49m[38;5;241;43m=[39;49m[43mrgi_filesuffix[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m)
[1;32m   1275[0m [38;5;28mself[39m[38;5;241m.[39mvalid_bounds [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39mflowline_mb_models[[38;5;241m-[39m[38;5;241m1[39m][38;5;241m.[39mvalid_bounds
[1;32m   1276[0m [38;5;28mself[39m[38;5;241m.[39mhemisphere [38;5;241m=[39m gdir[38;5;241m.[39mhemisphere

File [0;32m/usr/local/pyenv/versions/3.10.10/lib/python3.10/site-packages/oggm/core/massbalance.py:653[0m, in [0;36mConstantMassBalance.__init__[0;34m(self, gdir, mu_star, bias, y0, halfsize, filename, input_filesuffix, **kwargs)[0m
[1;32m    627[0m [38;5;250m[39m[38;5;124;03m"""Initialize[39;00m
[1;32m    628[0m 
[1;32m    629[0m [38;5;124;03mParameters[39;00m
[0;32m   (...)[0m
[1;32m    649[0m [38;5;124;03m    the file suffix of the input climate file[39;00m
[1;32m    650[0m [38;5;124;03m"""[39;00m
[1;32m    652[0m [38;5;28msuper[39m(ConstantMassBalance, [38;5;28mself[39m)[38;5;241m.[39m[38;5;21m__init__[39m()
[0;32m--> 653[0m [38;5;28mself[39m[38;5;241m.[39mmbmod [38;5;241m=[39m [43mPastMassBalance[49m[43m([49m[43mgdir[49m[43m,[49m[43m [49m[43mmu_star[49m[38;5;241;43m=[39;49m[43mmu_star[49m[43m,[49m[43m [49m[43mbias[49m[38;5;241;43m=[39;49m[43mbias[49m[43m,[49m
[1;32m    654[0m [43m                             [49m[43mfilename[49m[38;5;241;43m=[39;49m[43mfilename[49m[43m,[49m
[1;32m    655[0m [43m                             [49m[43minput_filesuffix[49m[38;5;241;43m=[39;49m[43minput_filesuffix[49m[43m,[49m
[1;32m    656[0m [43m                             [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m
[1;32m    658[0m [38;5;28;01mif[39;00m y0 [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m:
[1;32m    659[0m     df [38;5;241m=[39m gdir[38;5;241m.[39mread_json([38;5;124m'[39m[38;5;124mlocal_mustar[39m[38;5;124m'[39m)

File [0;32m/usr/local/pyenv/versions/3.10.10/lib/python3.10/site-packages/oggm/core/massbalance.py:370[0m, in [0;36mPastMassBalance.__init__[0;34m(self, gdir, mu_star, bias, filename, input_filesuffix, repeat, ys, ye, check_calib_params)[0m
[1;32m    368[0m         prcp_fac [38;5;241m=[39m gdir[38;5;241m.[39mread_json([38;5;124m'[39m[38;5;124mlocal_mustar[39m[38;5;124m'[39m)[[38;5;124m'[39m[38;5;124mglacier_prcp_scaling_factor[39m[38;5;124m'[39m]
[1;32m    369[0m     [38;5;28;01mexcept[39;00m [38;5;167;01mKeyError[39;00m:
[0;32m--> 370[0m         [38;5;28;01mraise[39;00m InvalidWorkflowError([38;5;124m'[39m[38;5;124mYou seem to be using directories [39m[38;5;124m'[39m
[1;32m    371[0m                                    [38;5;124m'[39m[38;5;124mwhich are not calibrated for a varying [39m[38;5;124m'[39m
[1;32m    372[0m                                    [38;5;124m'[39m[38;5;124mprcp factor. [39m[38;5;124m'[39m)
[1;32m    373[0m [38;5;28;01melse[39;00m:
[1;32m    374[0m     prcp_fac [38;5;241m=[39m cfg[38;5;241m.[39mPARAMS[[38;5;124m'[39m[38;5;124mprcp_scaling_factor[39m[38;5;124m'[39m]

[0;31mInvalidWorkflowError[0m: You seem to be using directories which are not calibrated for a varying prcp factor. 
InvalidWorkflowError: You seem to be using directories which are not calibrated for a varying prcp factor. 

