Traceback (most recent call last):
  File "/usr/local/pyenv/versions/3.10.7/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/usr/local/pyenv/versions/3.10.7/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/local/pyenv/versions/3.10.7/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/local/pyenv/versions/3.10.7/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/local/pyenv/versions/3.10.7/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/usr/local/pyenv/versions/3.10.7/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/usr/local/pyenv/versions/3.10.7/lib/python3.10/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/usr/local/pyenv/versions/3.10.7/lib/python3.10/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Since we overwrote the inversion flowlines we have to do stuff again
utils.apply_test_ref_tstars()
tasks.local_t_star(gdir)
tasks.mu_star_calibration(gdir)
tasks.prepare_for_inversion(gdir, add_debug_var=True)
tasks.mass_conservation_inversion(gdir)
tasks.compute_velocities(gdir)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mInvalidParamsError[0m                        Traceback (most recent call last)
Cell [0;32mIn [37], line 3[0m
[1;32m      1[0m [38;5;66;03m# Since we overwrote the inversion flowlines we have to do stuff again[39;00m
[1;32m      2[0m utils[38;5;241m.[39mapply_test_ref_tstars()
[0;32m----> 3[0m tasks[38;5;241m.[39mlocal_t_star(gdir)
[1;32m      4[0m tasks[38;5;241m.[39mmu_star_calibration(gdir)
[1;32m      5[0m tasks[38;5;241m.[39mprepare_for_inversion(gdir, add_debug_var[38;5;241m=[39m[38;5;28;01mTrue[39;00m)

File [0;32m/usr/local/pyenv/versions/3.10.7/lib/python3.10/site-packages/oggm/utils/_workflow.py:491[0m, in [0;36mentity_task.__call__.<locals>._entity_task[0;34m(gdir, reset, print_log, return_value, continue_on_error, add_to_log_file, **kwargs)[0m
[1;32m    489[0m     signal[38;5;241m.[39malarm(cfg[38;5;241m.[39mPARAMS[[38;5;124m'[39m[38;5;124mtask_timeout[39m[38;5;124m'[39m])
[1;32m    490[0m ex_t [38;5;241m=[39m time[38;5;241m.[39mtime()
[0;32m--> 491[0m out [38;5;241m=[39m [43mtask_func[49m[43m([49m[43mgdir[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m
[1;32m    492[0m ex_t [38;5;241m=[39m time[38;5;241m.[39mtime() [38;5;241m-[39m ex_t
[1;32m    493[0m [38;5;28;01mif[39;00m cfg[38;5;241m.[39mPARAMS[[38;5;124m'[39m[38;5;124mtask_timeout[39m[38;5;124m'[39m] [38;5;241m>[39m [38;5;241m0[39m:

File [0;32m/usr/local/pyenv/versions/3.10.7/lib/python3.10/site-packages/oggm/core/climate.py:983[0m, in [0;36mlocal_t_star[0;34m(gdir, ref_df, tstar, bias, clip_mu_star, min_mu_star, max_mu_star)[0m
[1;32m    947[0m [38;5;124;03m"""Compute the local t* and associated glacier-wide mu*.[39;00m
[1;32m    948[0m 
[1;32m    949[0m [38;5;124;03mIf ``tstar`` and ``bias`` are not provided, they will be interpolated from[39;00m
[0;32m   (...)[0m
[1;32m    980[0m [38;5;124;03m    defaults to cfg.PARAMS['max_mu_star'][39;00m
[1;32m    981[0m [38;5;124;03m"""[39;00m
[1;32m    982[0m [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m cfg[38;5;241m.[39mPARAMS[[38;5;124m'[39m[38;5;124muse_tstar_calibration[39m[38;5;124m'[39m]:
[0;32m--> 983[0m     [38;5;28;01mraise[39;00m InvalidParamsError([38;5;124m'[39m[38;5;124mIf using [39m[38;5;124m"[39m[38;5;124mold[39m[38;5;124m"[39m[38;5;124m mu* calibration, set [39m[38;5;124m'[39m
[1;32m    984[0m                              [38;5;124m"[39m[38;5;124mPARAMS[[39m[38;5;124m'[39m[38;5;124muse_tstar_calibration[39m[38;5;124m'[39m[38;5;124m] to True.[39m[38;5;124m"[39m)
[1;32m    986[0m [38;5;28;01mif[39;00m tstar [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m [38;5;129;01mor[39;00m bias [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m:
[1;32m    987[0m     [38;5;66;03m# Do our own interpolation[39;00m
[1;32m    988[0m     [38;5;28;01mif[39;00m ref_df [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m:
[1;32m    989[0m         [38;5;66;03m# Use the the local calibration[39;00m

[0;31mInvalidParamsError[0m: If using "old" mu* calibration, set PARAMS['use_tstar_calibration'] to True.
InvalidParamsError: If using "old" mu* calibration, set PARAMS['use_tstar_calibration'] to True.

