Traceback (most recent call last):
  File "/usr/local/pyenv/versions/3.10.10/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/usr/local/pyenv/versions/3.10.10/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/local/pyenv/versions/3.10.10/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/local/pyenv/versions/3.10.10/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/local/pyenv/versions/3.10.10/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/usr/local/pyenv/versions/3.10.10/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/usr/local/pyenv/versions/3.10.10/lib/python3.10/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/usr/local/pyenv/versions/3.10.10/lib/python3.10/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
workflow.execute_entity_task(tasks.run_from_climate_data, gdirs, 
                             output_filesuffix='_my_spinup',  # to use the files as input later on
                            );
ds = utils.compile_run_output(gdirs, input_filesuffix='_my_spinup')
ds.volume.plot(hue='rgi_id');
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
Cell [0;32mIn[6], line 1[0m
[0;32m----> 1[0m [43mworkflow[49m[38;5;241;43m.[39;49m[43mexecute_entity_task[49m[43m([49m[43mtasks[49m[38;5;241;43m.[39;49m[43mrun_from_climate_data[49m[43m,[49m[43m [49m[43mgdirs[49m[43m,[49m[43m [49m
[1;32m      2[0m [43m                             [49m[43moutput_filesuffix[49m[38;5;241;43m=[39;49m[38;5;124;43m'[39;49m[38;5;124;43m_my_spinup[39;49m[38;5;124;43m'[39;49m[43m,[49m[43m  [49m[38;5;66;43;03m# to use the files as input later on[39;49;00m
[1;32m      3[0m [43m                            [49m[43m)[49m;
[1;32m      4[0m ds [38;5;241m=[39m utils[38;5;241m.[39mcompile_run_output(gdirs, input_filesuffix[38;5;241m=[39m[38;5;124m'[39m[38;5;124m_my_spinup[39m[38;5;124m'[39m)
[1;32m      5[0m ds[38;5;241m.[39mvolume[38;5;241m.[39mplot(hue[38;5;241m=[39m[38;5;124m'[39m[38;5;124mrgi_id[39m[38;5;124m'[39m);

File [0;32m/usr/local/pyenv/versions/3.10.10/lib/python3.10/site-packages/oggm/workflow.py:191[0m, in [0;36mexecute_entity_task[0;34m(task, gdirs, **kwargs)[0m
[1;32m    187[0m     [38;5;28;01mif[39;00m ng [38;5;241m>[39m [38;5;241m3[39m:
[1;32m    188[0m         log[38;5;241m.[39mworkflow([38;5;124m'[39m[38;5;124mWARNING: you are trying to run an entity task on [39m[38;5;124m'[39m
[1;32m    189[0m                      [38;5;124m'[39m[38;5;132;01m%d[39;00m[38;5;124m glaciers with multiprocessing turned off. OGGM [39m[38;5;124m'[39m
[1;32m    190[0m                      [38;5;124m'[39m[38;5;124mwill run faster with multiprocessing turned on.[39m[38;5;124m'[39m, ng)
[0;32m--> 191[0m     out [38;5;241m=[39m [pc(gdir) [38;5;28;01mfor[39;00m gdir [38;5;129;01min[39;00m gdirs]
[1;32m    193[0m [38;5;28;01mreturn[39;00m out

File [0;32m/usr/local/pyenv/versions/3.10.10/lib/python3.10/site-packages/oggm/workflow.py:191[0m, in [0;36m<listcomp>[0;34m(.0)[0m
[1;32m    187[0m     [38;5;28;01mif[39;00m ng [38;5;241m>[39m [38;5;241m3[39m:
[1;32m    188[0m         log[38;5;241m.[39mworkflow([38;5;124m'[39m[38;5;124mWARNING: you are trying to run an entity task on [39m[38;5;124m'[39m
[1;32m    189[0m                      [38;5;124m'[39m[38;5;132;01m%d[39;00m[38;5;124m glaciers with multiprocessing turned off. OGGM [39m[38;5;124m'[39m
[1;32m    190[0m                      [38;5;124m'[39m[38;5;124mwill run faster with multiprocessing turned on.[39m[38;5;124m'[39m, ng)
[0;32m--> 191[0m     out [38;5;241m=[39m [[43mpc[49m[43m([49m[43mgdir[49m[43m)[49m [38;5;28;01mfor[39;00m gdir [38;5;129;01min[39;00m gdirs]
[1;32m    193[0m [38;5;28;01mreturn[39;00m out

File [0;32m/usr/local/pyenv/versions/3.10.10/lib/python3.10/site-packages/oggm/workflow.py:108[0m, in [0;36m_pickle_copier.__call__[0;34m(self, arg)[0m
[1;32m    106[0m [38;5;28;01mfor[39;00m func [38;5;129;01min[39;00m [38;5;28mself[39m[38;5;241m.[39mcall_func:
[1;32m    107[0m     func, kwargs [38;5;241m=[39m func
[0;32m--> 108[0m     res [38;5;241m=[39m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_call_internal[49m[43m([49m[43mfunc[49m[43m,[49m[43m [49m[43marg[49m[43m,[49m[43m [49m[43mkwargs[49m[43m)[49m
[1;32m    109[0m [38;5;28;01mreturn[39;00m res

File [0;32m/usr/local/pyenv/versions/3.10.10/lib/python3.10/site-packages/oggm/workflow.py:102[0m, in [0;36m_pickle_copier._call_internal[0;34m(self, call_func, gdir, kwargs)[0m
[1;32m     99[0m     gdir, gdir_kwargs [38;5;241m=[39m gdir
[1;32m    100[0m     kwargs[38;5;241m.[39mupdate(gdir_kwargs)
[0;32m--> 102[0m [38;5;28;01mreturn[39;00m [43mcall_func[49m[43m([49m[43mgdir[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m

File [0;32m/usr/local/pyenv/versions/3.10.10/lib/python3.10/site-packages/oggm/utils/_workflow.py:491[0m, in [0;36mentity_task.__call__.<locals>._entity_task[0;34m(gdir, reset, print_log, return_value, continue_on_error, add_to_log_file, **kwargs)[0m
[1;32m    489[0m     signal[38;5;241m.[39malarm(cfg[38;5;241m.[39mPARAMS[[38;5;124m'[39m[38;5;124mtask_timeout[39m[38;5;124m'[39m])
[1;32m    490[0m ex_t [38;5;241m=[39m time[38;5;241m.[39mtime()
[0;32m--> 491[0m out [38;5;241m=[39m [43mtask_func[49m[43m([49m[43mgdir[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m
[1;32m    492[0m ex_t [38;5;241m=[39m time[38;5;241m.[39mtime() [38;5;241m-[39m ex_t
[1;32m    493[0m [38;5;28;01mif[39;00m cfg[38;5;241m.[39mPARAMS[[38;5;124m'[39m[38;5;124mtask_timeout[39m[38;5;124m'[39m] [38;5;241m>[39m [38;5;241m0[39m:

File [0;32m/usr/local/pyenv/versions/3.10.10/lib/python3.10/site-packages/oggm/core/flowline.py:3704[0m, in [0;36mrun_from_climate_data[0;34m(gdir, ys, ye, min_ys, max_ys, fixed_geometry_spinup_yr, store_monthly_step, store_model_geometry, store_fl_diagnostics, climate_filename, mb_model, climate_input_filesuffix, output_filesuffix, init_model_filesuffix, init_model_yr, init_model_fls, zero_initial_glacier, bias, temperature_bias, precipitation_factor, **kwargs)[0m
[1;32m   3701[0m     ys [38;5;241m=[39m ys [38;5;28;01mif[39;00m ys [38;5;241m<[39m max_ys [38;5;28;01melse[39;00m max_ys
[1;32m   3703[0m [38;5;28;01mif[39;00m mb_model [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m:
[0;32m-> 3704[0m     mb_model [38;5;241m=[39m [43mMultipleFlowlineMassBalance[49m[43m([49m[43mgdir[49m[43m,[49m
[1;32m   3705[0m [43m                                           [49m[43mmb_model_class[49m[38;5;241;43m=[39;49m[43mPastMassBalance[49m[43m,[49m
[1;32m   3706[0m [43m                                           [49m[43mfilename[49m[38;5;241;43m=[39;49m[43mclimate_filename[49m[43m,[49m
[1;32m   3707[0m [43m                                           [49m[43mbias[49m[38;5;241;43m=[39;49m[43mbias[49m[43m,[49m
[1;32m   3708[0m [43m                                           [49m[43minput_filesuffix[49m[38;5;241;43m=[39;49m[43mclimate_input_filesuffix[49m[43m)[49m
[1;32m   3710[0m [38;5;28;01mif[39;00m temperature_bias [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m:
[1;32m   3711[0m     mb_model[38;5;241m.[39mtemp_bias [38;5;241m=[39m temperature_bias

File [0;32m/usr/local/pyenv/versions/3.10.10/lib/python3.10/site-packages/oggm/core/massbalance.py:1272[0m, in [0;36mMultipleFlowlineMassBalance.__init__[0;34m(self, gdir, fls, mu_star, mb_model_class, use_inversion_flowlines, input_filesuffix, bias, **kwargs)[0m
[1;32m   1267[0m             [38;5;28;01mraise[39;00m InvalidParamsError([38;5;124m'[39m[38;5;124mt_star has not been set for this [39m[38;5;124m'[39m
[1;32m   1268[0m                                      [38;5;124m'[39m[38;5;124mglacier. Please set `y0` explicitly[39m[38;5;124m'[39m)
[1;32m   1269[0m         kwargs[[38;5;124m'[39m[38;5;124my0[39m[38;5;124m'[39m] [38;5;241m=[39m y0
[1;32m   1271[0m     [38;5;28mself[39m[38;5;241m.[39mflowline_mb_models[38;5;241m.[39mappend(
[0;32m-> 1272[0m         mb_model_class(gdir, mu_star[38;5;241m=[39m[43mfl[49m[38;5;241;43m.[39;49m[43mmu_star[49m, bias[38;5;241m=[39mfl_bias,
[1;32m   1273[0m                        input_filesuffix[38;5;241m=[39mrgi_filesuffix, [38;5;241m*[39m[38;5;241m*[39mkwargs))
[1;32m   1275[0m [38;5;28mself[39m[38;5;241m.[39mvalid_bounds [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39mflowline_mb_models[[38;5;241m-[39m[38;5;241m1[39m][38;5;241m.[39mvalid_bounds
[1;32m   1276[0m [38;5;28mself[39m[38;5;241m.[39mhemisphere [38;5;241m=[39m gdir[38;5;241m.[39mhemisphere

[0;31mAttributeError[0m: 'MixedBedFlowline' object has no attribute 'mu_star'
AttributeError: 'MixedBedFlowline' object has no attribute 'mu_star'

