Traceback (most recent call last):
  File "/usr/local/pyenv/versions/3.9.8/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/usr/local/pyenv/versions/3.9.8/lib/python3.9/site-packages/nbclient/client.py", line 1085, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/local/pyenv/versions/3.9.8/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/local/pyenv/versions/3.9.8/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/local/pyenv/versions/3.9.8/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/usr/local/pyenv/versions/3.9.8/lib/python3.9/site-packages/nbclient/client.py", line 551, in async_execute
    await self.async_execute_cell(
  File "/usr/local/pyenv/versions/3.9.8/lib/python3.9/site-packages/nbclient/client.py", line 846, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/usr/local/pyenv/versions/3.9.8/lib/python3.9/site-packages/nbclient/client.py", line 748, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
gdirs[0].get_filepath('dem').replace(WORKING_DIR, 'WORKING_DIR')
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Input [0;32mIn [5][0m, in [0;36m<module>[0;34m[0m
[0;32m----> 1[0m gdirs[[38;5;241m0[39m][38;5;241m.[39mget_filepath([38;5;124m'[39m[38;5;124mdem[39m[38;5;124m'[39m)[38;5;241m.[39mreplace([43mWORKING_DIR[49m, [38;5;124m'[39m[38;5;124mWORKING_DIR[39m[38;5;124m'[39m)

[0;31mNameError[0m: name 'WORKING_DIR' is not defined
NameError: name 'WORKING_DIR' is not defined

