Traceback (most recent call last):
  File "/usr/local/pyenv/versions/3.9.10/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/usr/local/pyenv/versions/3.9.10/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/local/pyenv/versions/3.9.10/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/local/pyenv/versions/3.9.10/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/local/pyenv/versions/3.9.10/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/usr/local/pyenv/versions/3.9.10/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/usr/local/pyenv/versions/3.9.10/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/usr/local/pyenv/versions/3.9.10/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import warnings
warnings.filterwarnings("ignore")  # sklearn sends a lot of warnings
# Scikit learn (can be installed e.g. via conda install -c anaconda scikit-learn)
from sklearn.linear_model import LassoCV
from sklearn.model_selection import KFold
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mImportError[0m                               Traceback (most recent call last)
Input [0;32mIn [21][0m, in [0;36m<cell line: 4>[0;34m()[0m
[1;32m      2[0m warnings[38;5;241m.[39mfilterwarnings([38;5;124m"[39m[38;5;124mignore[39m[38;5;124m"[39m)  [38;5;66;03m# sklearn sends a lot of warnings[39;00m
[1;32m      3[0m [38;5;66;03m# Scikit learn (can be installed e.g. via conda install -c anaconda scikit-learn)[39;00m
[0;32m----> 4[0m [38;5;28;01mfrom[39;00m [38;5;21;01msklearn[39;00m[38;5;21;01m.[39;00m[38;5;21;01mlinear_model[39;00m [38;5;28;01mimport[39;00m LassoCV
[1;32m      5[0m [38;5;28;01mfrom[39;00m [38;5;21;01msklearn[39;00m[38;5;21;01m.[39;00m[38;5;21;01mmodel_selection[39;00m [38;5;28;01mimport[39;00m KFold

File [0;32m/usr/local/pyenv/versions/3.9.10/lib/python3.9/site-packages/sklearn/__init__.py:83[0m, in [0;36m<module>[0;34m[0m
[1;32m     81[0m     [38;5;28;01mfrom[39;00m [38;5;21;01m.[39;00m [38;5;28;01mimport[39;00m __check_build  [38;5;66;03m# noqa: F401[39;00m
[1;32m     82[0m     [38;5;28;01mfrom[39;00m [38;5;21;01m.[39;00m[38;5;21;01mbase[39;00m [38;5;28;01mimport[39;00m clone
[0;32m---> 83[0m     [38;5;28;01mfrom[39;00m [38;5;21;01m.[39;00m[38;5;21;01mutils[39;00m[38;5;21;01m.[39;00m[38;5;21;01m_show_versions[39;00m [38;5;28;01mimport[39;00m show_versions
[1;32m     85[0m     __all__ [38;5;241m=[39m [
[1;32m     86[0m         [38;5;124m"[39m[38;5;124mcalibration[39m[38;5;124m"[39m,
[1;32m     87[0m         [38;5;124m"[39m[38;5;124mcluster[39m[38;5;124m"[39m,
[0;32m   (...)[0m
[1;32m    128[0m         [38;5;124m"[39m[38;5;124mshow_versions[39m[38;5;124m"[39m,
[1;32m    129[0m     ]
[1;32m    132[0m [38;5;28;01mdef[39;00m [38;5;21msetup_module[39m(module):

File [0;32m/usr/local/pyenv/versions/3.9.10/lib/python3.9/site-packages/sklearn/utils/_show_versions.py:12[0m, in [0;36m<module>[0;34m[0m
[1;32m      9[0m [38;5;28;01mimport[39;00m [38;5;21;01msys[39;00m
[1;32m     10[0m [38;5;28;01mimport[39;00m [38;5;21;01mimportlib[39;00m
[0;32m---> 12[0m [38;5;28;01mfrom[39;00m [38;5;21;01m.[39;00m[38;5;21;01m_openmp_helpers[39;00m [38;5;28;01mimport[39;00m _openmp_parallelism_enabled
[1;32m     15[0m [38;5;28;01mdef[39;00m [38;5;21m_get_sys_info[39m():
[1;32m     16[0m     [38;5;124;03m"""System information[39;00m
[1;32m     17[0m 
[1;32m     18[0m [38;5;124;03m    Returns[39;00m
[0;32m   (...)[0m
[1;32m     22[0m 
[1;32m     23[0m [38;5;124;03m    """[39;00m

[0;31mImportError[0m: libgomp.so.1: cannot open shared object file: No such file or directory
ImportError: libgomp.so.1: cannot open shared object file: No such file or directory

